Fix command injection vulnerability
418sec/heroku-addonpool pull request #1
Opened 2020-04-17 17:41 UTC by 69

I've replaced all instances of `exec` within the code with `execFile` and slightly modified the workflow of the `supplyReset` function to get rid of the pipe to grep.

2020-04-21 02:51 UTC, Kristoff-Harris commented
@69 this looks good to me! I'm not a sherif, just taking a look because I thought this bounty was till open. Just out of curiosity, was there a way to exploit that this PR is remediating?

2020-04-24 11:13 UTC, adam-nygate commented
> @69 this looks good to me! I'm not a sherif, just taking a look because I thought this bounty was till open. Just out of curiosity, was there a way to exploit that this PR is remediating?

Hey @Kristoff-Harris, just stepping in here for @69. A PoC for the exploit can be found [here](https://www.huntr.dev/app/bounties/open/070-js-heroku-addonpool), but to summarise, we've seen some uses of this package where external (user) input, can be provided to the Root constructor, leading to Command Injection.

Looking forward to seeing you active in the community!

-Adam

2020-04-24 15:21 UTC, adam-nygate requested changes
Hi,

Can you add more information into the PR description, describing your contribution?

-Adam

2020-04-24 17:15 UTC, Kristoff-Harris commented
@adam-nygate Please take a look at this https://github.com/nodef/heroku-addonpool/commit/b1a5b316473ac92d783f3d54ee048d54082da38d

If you run the POC in [RunKit](https://npm.runkit.com/heroku-addonpool) with heroku-addonpool 0.1.16, you'll see the regex that wolfram77 introduced has fixed that specific abuse case in the Huntr.dev ticket. I'm curious if @69 knew of another exploit that could bypass Wolfram77's fix.

2020-04-27 10:53 UTC, adam-nygate commented
> @adam-nygate Thanks for the warm welcome! I'm really excited to get involved :)
> If you have a moment, please take a look at this [nodef@b1a5b31](https://github.com/nodef/heroku-addonpool/commit/b1a5b316473ac92d783f3d54ee048d54082da38d)
> 
> If you run the POC in [RunKit](https://npm.runkit.com/heroku-addonpool) with heroku-addonpool 0.1.16, you'll see the regex that wolfram77 introduced has fixed that specific abuse case in the Huntr.dev ticket. I'm curious if @69 knew of another exploit that could bypass Wolfram77's fix.

@Kristoff-Harris yeah I think you're right! This must have squeezed through our checks on a disclosure that was made to our platform. Thanks for the spot!

Also, in case you haven't heard, we just started paying out for disclosures. Feel free to check it out here: https://www.huntr.dev/app/bounties/disclose

2020-04-27 10:53 UTC, closed without merging